### ISSUE TITLE
initial features

### ISSUE THREAD

**Issue by crcn** [crcn/figmark#11]
#### TODO

- [x] layer blend mode
- [x] linear fill
- [x] angular fill 
- [x] diamond fill
- [x] Image fill
- [x] solid fill
- [x] drop shadow effect
- [x] inner shadow effect
- [x] layer blur effect
- [x] background blur
- [x] load SVGs
- [ ] load fonts somehow
- [x] if export, then use that instead of layer
- [ ] ~~auto layout~~
- [x] shape stroke
- [ ] ~~color variables~~
- [ ] ~~typography groups~~
- [x] import components

**Comment by crcn** [comment]
Skipping color vars for now until the library is polished.

**Comment by crcn** [comment]
Fonts aren't doable since Figma doesn't have an API for that. Developers will have to manually load them in.
